@startuml

abstract class Person {
    -name: String
    -age: int
}

class Student extends Person implements Comparable{
    -id: int
    -{static} generalId: int
    __
    ..Getters&Setters..
    +getId(): int
    ..@Override..
    +toString(): String
    +compareTo(): int
}

class StudentGroup implements Iterable, Comparable {
    -idGroup: Integer
    -group: List<Student>
    __
    +add()
    ..Getters&Setters..
    +getGroup(): List<Student>
    +setGroup()
    +getIdGroup(): Integer
    +setIdGroup()
    ..@Override..
    +toString(): String
    +iterator(): StudentIterator
    +compareTo()
}

class StudentSteam implements Iterable {
    -steamNumber: int
    -groups: List<StudentGroup>
    __
    +add()
    +remove(): boolean
    +getGroups(): List<StudentGroup>
    +sortSteam()
    ..@Override..
    +toString(): String
    +iterator(): GroupIterator
}

class StudentIterator implements Iterator {
    -counter: int
    -students: List<Student>
    __
    ..@Override..
    +hasNext()
    +next(): Student
}

class GroupIterator implements Iterator {
    -counter: int
    -groups: List<StudentGroup>
    __
    ..@Override..
    +hasNext()
    +next(): StudentGroup
}

interface Comparable

StudentGroup <|--* Student
StudentGroup <|--* StudentIterator
StudentGroup --* Student

StudentSteam <|--* StudentGroup
StudentSteam <|--* GroupIterator
StudentSteam --* StudentGroup

'class Employee extends Person
'class Teacher extends Person

hide @unlinked
@enduml